version: "3.8"
services:

  jenkins:
    user: root
    image: contact-app-jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      #- "/var/lib/docker/volumes/jenkins_home/_data:/var/jenkins_home"
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
